wazo-platform/asterisk

.gitignore
README.md
debian/patches/series
debian/patches/wazo_sip_mobility

W799 sip mobility

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues
debian/rules

This branch is under load test with the package version `8:16.4.1-1~wazo1`
Once all test are satisfying this branch will be merge-able without bumping its `debian/changelog`

upgrade to Asterisk 16.4.1

---

debian/source/options
zuul.yaml

Depends-On: https://github.com/wazo-platform/sf-jobs/pull/17

add zuul.yaml

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues
debian/rules

I pushed the same modifications on branch asterisk-rc which should execute a few days on the load servers before merging this PR.

WAZO-1206 upgrade to Asterisk 16.6.0

---

.gitignore
debian/changelog
debian/source/options
integration_tests/Makefile
integration_tests/test-requirements.txt
tox.ini
zuul.yaml

Depends-On: https://github.com/wazo-platform/sf-jobs/pull/28

integration tests pass in python3

---

debian/changelog
debian/tests/control
debian/tests/integration-tests
debian/tests/testsuite
debian/tests/unittests
integration_tests/Makefile
integration_tests/docker-build.sh
integration_tests/test-requirements.txt
zuul.yaml

Depends-On: https://github.com/wazo-platform/sf-jobs/pull/32

run the tests in the same zuul job as the build

---

README.md
debian/changelog
debian/rules
integration_tests/Makefile
integration_tests/docker-build.sh
integration_tests/test-requirements.txt

Depends-On: https://github.com/wazo-platform/sf-jobs/pull/40

integration_tests/Makefile: do not pull images

---

debian/changelog
debian/patches/revert_asterisk_commit_with_race_condition
integration_tests/test-requirements.txt

add link to the asterisk bug tracker for a patch
remove pyhamcrest version constraint

Pull request for add-asterisk-issue-to-patch

---

debian/changelog
debian/patches/asterisk_13792_bad_audio_incomplete_dtls_srtp_setup
debian/patches/series
debian/tests/control
debian/tests/integration-tests

Why:
* See upstream description:
https://gerrit.asterisk.org/c/asterisk/+/137920

backport upstream patch for bad audio

---

debian/asterisk.postinst
debian/changelog

remove old unused migration section
debian: fix command location

Pull request for remove-old-postinst

---

debian/changelog
debian/patches/colp-patch.diff
debian/patches/series
debian/patches/wazo_bridge_variables

Depends-On: https://github.com/wazo-platform/asterisk/pull/50

Wp 77 wrong connected line

---

debian/changelog
debian/patches/colp-patch.diff
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

the banner patch has been updated for the security fix only warning

WAZO-2107 asterisk 17.9.0

---

debian/asterisk.postinst
debian/asterisk_fix
debian/changelog

the init file is not used anymore and can be removed from installs that still
have it

remove /etc/init.d/asterisk file

---

debian/changelog
debian/patches/wazo_mixmonitor_events

Depends-On: https://github.com/wazo-platform/asterisk/pull/62

Wazo 2223 mix monitor cel event

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Load tests started on 2021-02-18T20:08:00+0

Upgrade to Asterisk 18.2.1

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

asterisk-rc is in version `~wazo1` this PR is in `~wazo2` to avoid having to rebase when it's time to merge.
Load tests started on 2021-05-11 13:23:00+0

Upgrade to Asterisk 18.4.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Load tests have been started on 2021-06-29 19:15 UTC

upgrade to Asterisk 18.5.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/wazo_stun_timeout_error
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

the asterisk-rc branch is in a lower version so this branch can be merged as is.
Load test started on 2021-07-23 10:30:00-0400

upgrade to Asterisk 18.5.1

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

the following patches needed manual work to apply properly
- xivo_skill_queues
- wazo_stun_recurring_resolution
wazo-load started 2021-01-18 15:45

WAZO-2664 upgrade to Asterisk 18.9.0

---

debian/changelog
debian/patches/ASTERISK-29821
debian/patches/series

Fixes ASTERISK-29821/WAZO-2675

backport fix from asterisk 18.10.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Load test started at: 2022-03-04 16:00 UTC-5

upgrade asterisk 18.10.1

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Load tests started on Mon 16 May 2022 01:01:30 PM EDT

Upgrade to asterisk 18.12.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Load tests started on Mon 27 Jun 2022 03:29:48 PM EDT

WAZO-2798 upgrade to Asterisk 19.5.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Asterisk 19.6.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Load tests started on Wed 07 Dec 2022 10:05:37 AM EST

upgrade to Asterisk 19.7.1

---

debian/changelog
debian/patches/revert-30244.diff
debian/patches/series

Reason: ASTERISK-30244 fix introduces a big regression in WebRTC SIP status

WAZO-2977 revert asterisk 30244

---

debian/changelog
tox.ini

changes:
* whitelist_externals -> allowlist_externals

fix tox.ini for tox4

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Patches did not need to be modified. No fuzz while applying patches.

WAZO-2906: update to Asterisk 20.1.0

---

zuul.yaml

https://wazo-dev.atlassian.net/browse/WAZO-3254

Bullseye zuul update

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/fix-invalid-moh
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

patch manually updated:
- xivo_skill_queues app_queue
- fix-invalid-moh
Load test started at 2023-07-24 15:40:00 -4:00

bump version 20.4.0

---

debian/changelog

https://wazo-dev.atlassian.net/browse/WAZO-3445

bump version

---

debian/changelog
debian/patches/ASTERISK-386-memory-load-ephemeral-dtls-certs
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/fix-invalid-moh
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

all patches updated with no fuzz

upgrade to asterisk 20.5.2

---

debian/changelog
debian/patches/WAZO-3724-sigchild-return-value
debian/patches/asterisk-PR-888-crash-res-rtp-asterisk
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/fix-invalid-moh
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/series
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_skill_queues

reference issue: https://github.com/asterisk/asterisk/issues/487
reference PR: https://github.com/asterisk/asterisk/pull/888

Pull request for WP-1494-dtls-crash

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/fix-invalid-moh
debian/patches/increase-max-sdp-media
debian/patches/mix_monitor_announce_file
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_skill_queues

Note: conflict detected and resolved for `xivo_skill_queues` patch
Load tests started at: 2024-02-24 15:00:00 (EST)
I'll wait at least one day before switching PR to ready with `mergeit` tag

Pull request for WAZO-4074-asterisk-22.2.0

---

debian/changelog
debian/patches/asterisk-PR-1136-revert-set-mark-on-rtp
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/fix-application-playback-update
debian/patches/fix-invalid-moh
debian/patches/increase-max-sdp-media
debian/patches/mix_monitor_announce_file
debian/patches/mixmonitor_close_beep_file
debian/patches/series
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_skill_queues

This reverts commit 733da8823c100c0b74bc82415b1e37b98ae86fcb, reversing
changes made to 813bae13c15478436e2eaf3d8b82d66ac9a010b1.
PRE-MERGE: cleanup mirror
POSt-MERGE: downgrade shared dev stacks and quick announce for other devs

Revert "Merge pull request #154 from wazo-platform/WAZO-4119-asterisk-22.3.0"

---

Dockerfile
debian/changelog

why: to avoid issue with Jenkins because of last revert commit

Pull request for WAZO-4119-rebuild

---

debian/changelog
debian/patches/fix-queue-deadlock
debian/patches/series

Load tests have been started on 2025-06-09 18:02 UTC

[WP-1871] app_queue: use shared member object for shared_lastcall
