debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues
debian/rules

Version 16.6.1-1~wazo1 has been pushed to asterisk-rc on 2019-10-21 14:30 UTC allow the load tests to run over a few days before merging

upgrade to Asterisk 16.6.1

---

debian/asterisk.dirs
debian/asterisk.lintian-overrides
debian/asterisk.service
debian/changelog
debian/control
debian/rules

these modules are not loaded by default with the Wazo configuration but the
dependencies are all pulled when installing Asterisk. This change removes those
explicit dependencies.
another package will be added to pull down all dependencies that will be
installed manually if one of them is used

rules: exclude modules that are not loaded and pull extra deps

---

debian/changelog

I cannot leave ~4 because ~wazo3 is higher
```
dpkg --compare-versions "8:16.6.2-1~wazo3" "lt" "8:16.6.2-1~wazo4"
0
```
```
dpkg --compare-versions "8:16.6.2-1~wazo3" "lt" "8:16.6.2-1~4"
1
```

fix a mistake in the changelog version

---

debian/asterisk.service
debian/changelog

reason: new version of systemd (241-7~deb10u3) add a commit:
* core: change ownership/mode of the execution directories also for
static users

add User asterisk to asterisk.service

---

README.md

this avoid having to remove the markdown around the quoted strings when
copy/pasting commands to a shell

readme: use codeblocks for commands

---

debian/changelog
debian/control
debian/rules

Depends-On: https://github.com/wazo-platform/wazo-asterisk-doc-extractor/pull/2
Depends-On: https://github.com/wazo-platform/xivo-build-tools/pull/16

asterisk-doc: add the JSON extracted version of the PJSIP doc

---

debian/asterisk.postinst
debian/changelog

in wazo-res-stasis-amqp we have a drop-in file that modifies the API spec
because the module adds resources to the HTTP API.
since the ExecPreStart is now run as user "asterisk", it fails to apply the
change and asterisk cannot start.
related commit: 84dd6972a914ef8c7545155f9ecd7b2a82e6479b

postinst: chown rest-api spec files

---

debian/changelog
debian/control
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/e2c5d29.diff
debian/patches/fbb9359.diff
debian/patches/series
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

Also use libsrtp0 1.5.4 instead of libsrtp 2
https://wiki.asterisk.org/wiki/display/AST/libsrtp
The branch `asterisk-rc` as the same changes but is in version `~wazo3`
~~Load tests started at 2020-04-30 18:08 UTC~~
Load tests started at 2020-05-05 14:12 UTC
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1749

WAZO-1749 Asterisk 17.4.0

---

debian/asterisk.logrotate
debian/changelog

Why:
* logger-reload was only available in init.d file, not anymore with
systemd

logrotate: fix asterisk logger reload

---

debian/changelog
debian/patches/colp-patch.diff
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

no fuzz on patches
The version is suffixed `~wazo2` to allow smooth upgrades from asterisk-rc which is `~wazo1`
Load tests have been started on 2020-09-30 at 17:30 UTC

Upgrade to Asterisk 17.7.0

---

debian/changelog
debian/patches/colp-patch.diff
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_bridge_variables
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_banner
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

The version in the Debian changelog ends with `~wazo2` and the one in the `asterisk-rc` branch is `~wazo1`. This means that this branch can be merged without messing with the changelog when ready.

Upgrade patches for Asterisk 17.8.0

---

debian/changelog
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

xivo_skill_queues: Indentation change in 2 hunks
wazo_mixmonitor_events: Remove code that was in the patch to match the 18 branch
when the patch got written that is unrelated
The version in this branch is suffixed by `~2` the version in asterisk-rc is `~1`. No fiddling has to be done when we are ready to merge.
Load tests launched on 2021-01-26 10:00:00 EST

update for Asterisk 18.2.0

---

debian/changelog
debian/patches/series
debian/patches/wazo_stun_recurring_resolution
debian/patches/wazo_stun_timeout_error

Why:
* If the IP address of the STUN server changes, Asterisk will continue
connecting to the old IP address until the RTP module is reloaded.

add stun recurring resolution + stun timeout message

---

integration_tests/suite/test_voicemail.py
zuul.yaml

reason: service_port() returns only port bound to ipv4. Some host can
resolve localhost to ipv6 address and docker doesn't necessarily bind
the same port number on ipv4 and ipv6

test: use explicit ipv4 addr to connect docker

---

debian/changelog
debian/patches/wazo_stun_recurring_resolution
debian/patches/wazo_stun_timeout_error

Why:
* When disabling stunaddr, the recurring DNS resolution would continue
and restore stunaddr to the old value.

stun: fix disabling stunaddr

---

debian/changelog
debian/patches/wazo_stun_recurring_resolution

Why:
* If the TTL received from the DNS server is zero, meaning the
cache has expired, the recurring DNS would terminate itself.
With this fix, if a TTL of zero is received, a default value of
30 second is applied to the next query.
This 30 second delay avoids spamming the DNS server unnecessarily
if received TTL is always zero.
This change addresses the need by:
* If STUN server resolution stops, and the server is down, every
connection in Asterisk will timeout for 10 seconds while trying to
reach the STUN server, severely degrading user experience.

Fix TTL zero stopping recurring STUN resolution

---

debian/changelog
debian/patches/wazo_stun_recurring_resolution

Why:
* In a rare case where rtp module is restarted and a call comes in,
the stun address is null and asterisk segfaults.  This fix adds a guard
to prevent stun->address from returning a null value

WAZO-2646 Add null check for stun->address

---

debian/changelog
debian/patches/wazo_stun_recurring_resolution

Why:
* During a reload, this can lead to an invalid pointer dangling and
reused on a second reload.

stun-recurring-resolution: fix clearing of DNS resolver upon unload

---

debian/changelog
debian/patches/wazo_sip_mobility

for any given AOR only one mobile contact can be registered

WAZO-2765-remove-existing-mobile

---

debian/changelog
debian/patches/mixmonitor_close_beep_file
debian/patches/series

If channel is hungup before the beep is played, the file descriptor will stay stuck opened.
This happens when a user does not stop recording before hanging up.  The beep file and the stream will be 
opened but won't play and resources will not be cleaned up afterwards.
This patch makes sure to close the stream (and the file) if the beep couldn't be played.
_Strategy to test this issue:_
1. Get asterisk proc_id: ps -C asterisk
2. ls -la /proc/{procid}/fd
3. check list to see if any are using beep.slin
4. Call a number that will answer (*10 works) and start recording (*3 by default), then end the call (without stopping recording).
5. Repeat step 4 multiple time
6. repeat step 2 and 3 (without fix, should be multiple `beep.slin` still opened)

WAZO-2860: Close file on error playing beep

---

debian/asterisk.dirs
debian/asterisk.install
debian/changelog
debian/control

why: dh-systemd is included in debhelper 12. It will also remove a patch
for asterisk-vanilla and asterisk-debug

use debhelper to install asterisk.service file

---

debian/changelog
debian/control

why: dh-systemd is already included in debhelper 10

remove unused dh-systemd dependency

---

debian/changelog
debian/patches/fix-invalid-moh
debian/patches/series

Why: if an invalid WAV file is provided in a MOH class, it causes
asterisk to stop playback of the music. In the case of a call transfer,
people may hear eachother when it is unwanted. Call holding also does
not work because the music never plays.
This patch fixes the issue by removing the culprit MOH class. However,
it only works after the first occurence of the issue. The first time the
MOH is played will still present the problematic behavior.

res_musiconhold: remove invalid moh class when it cannot playback

---

debian/changelog
debian/patches/ASTERISK-386-memory-load-ephemeral-dtls-certs
debian/patches/series

asterisk issue: https://github.com/asterisk/asterisk/issues/386
Load tests started on `Mon 30 Oct 2023 02:15:00 PM UTC`

backport ephemeral dtls cert memory leak fix

---

debian/changelog
debian/patches/ASTERISK-386-memory-load-ephemeral-dtls-certs
debian/patches/deb_astgenkey-security
debian/patches/deb_make-clean-fixes
debian/patches/fix-invalid-moh
debian/patches/increase-max-sdp-media
debian/patches/mixmonitor_close_beep_file
debian/patches/wazo_ari_expose_voicemail_functions
debian/patches/wazo_banner
debian/patches/wazo_bridge_variables
debian/patches/wazo_mixmonitor_events
debian/patches/wazo_sip_mobility
debian/patches/wazo_stun_recurring_resolution
debian/patches/xivo_agent_complete_ast11_compat
debian/patches/xivo_agent_complete_wrapup
debian/patches/xivo_ari_events_moh
debian/patches/xivo_ari_set_channel_var_bypass
debian/patches/xivo_ccss_exten_context_var
debian/patches/xivo_channel_check_lock
debian/patches/xivo_dtmf_workaround_when_no_rtp
debian/patches/xivo_dtmf_xfer_plus
debian/patches/xivo_queue_agent_talking
debian/patches/xivo_queue_caller_leave_ast11_compat
debian/patches/xivo_queue_digits_gender
debian/patches/xivo_queue_update_queue_before_agent_complete
debian/patches/xivo_senddigit_begin
debian/patches/xivo_sip_tel_uri
debian/patches/xivo_skill_queues

no patch modification done, only line number changes
Depends-On: https://github.com/wazo-platform/asterisk-vanilla/pull/5
I added asterisk-vanilla as a dependency to get it merged first and avoid incrementing the version numbers for the sake of rebuilding if we are doing it in reverse order.

asterisk 20.5.0

---

debian/asterisk.service
debian/changelog
debian/control

Why:
* Reduces memory usage for long-running processes

use TCMalloc memory allocator

---

debian/asterisk.postinst
debian/changelog

Why: by removing the xivo-fix-paths-rights script, we need to chown more directories that were chown'ed by the script.

[WAZO-3723] Add more directory permissions to the packaging

---

debian/changelog
debian/patches/mix_monitor_announce_file
debian/patches/series

This PR can be tested with a modification to the `/etc/xivo/asterisk/xivo_globals.conf` file with the following values
```
; MixMonitor
WAZO_MIXMONITOR_OPTIONS = p(/usr/share/asterisk/sounds/fr_FR/record-call-on)P(/usr/share/asterisk/sounds/fr_FR/record-call-off)
; WAZO_MIXMONITOR_OPTIONS = p(record-call-on)P(record-call-off)
; WAZO_MIXMONITOR_OPTIONS = pP
```
The `pP` version should play "beep"
Removing the variable should result in no sound on start and stop

Wazo 4031 mixmonitor announce file

---

debian/asterisk-dev.install
debian/asterisk-dev.links

why: fix issue with custom modules (ex: wazo-res-consul-stasis-app)

WAZO-4326-bookworm
